### PR TITLE
Readme cleanup

### PR DESCRIPTION
**Pull request by drawcard**
Just thought I would help with a bit of a tidy of the README file, to make it easier to understand for new users, as well as fix a few typos / grammatical issues. Please approve or reject whatever you see fit. Thanks

### CODE REVIEW

**Comment by nuritsha** [comment]
Thanks a lot for taking the time and helping us improve. 
We have reviewed the PR and adopted some of changes you proposed. You should be able to see them in the next release.
BTW - we have submitted the theme to WordPress and hope to get it approved soon.
Just one minor comment regarding your suggestions - the theme is "plain-vanilla", as in "basic" rather than based on Vanilla theme... :)

**Comment by drawcard** [comment]
Thanks @nuritsha - appreciate the follow up :)

**Comment by drawcard** [comment]
@nuritsha one question, I have since deleted the fork that I made the edits on, so they are now orphaned. Would you like me to submit a new PR from a new fork, replaying my edits into it? Or can you work with what I've made so far?

**Comment by nuritsha** [comment]
Hi @drawcard,
Sorry for the (very) late response...
Your changes & suggestions were merged manually, no need for a new PR.
Thanks!

**Comment by drawcard** [comment]
Thanks @nuritsha - could I also please put in a request to allow issue reporting at this repo? I’ve had to report bugs for this template at the main Elementor repo and it’s not ideal :)

**Comment by nuritsha** [comment]
Not ideal indeed. Thanks for pointing that out! Should change soon.

**Comment by nuritsha** [comment]
https://wordpress.org/themes/hello-elementor

**Comment by drawcard** [comment]
Wow this is so good having the Hello theme on the Wordpress theme directory, so much easier to automatically deploy on client sites now. Thanks @nuritsha :)

**Comment by nuritsha** [comment]
many thanks!

**Pull request closed without merging**
